version: '3.8'

services:
  client:
    build:
      context: ./client/my-remix-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
      - ./server/migrations:/app/migrations

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - type: bind
        source: C:\data\db
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"