name: Publish Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code # Fixed indentation and spacing after the "-"
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image Client
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-remix-app:latest ./client/my-remix-app

      - name: Build Docker Image Server
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-remix-app-server:latest ./server
